services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendFRA
    container_name: frontendFRA
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebFRA
  backend:
    build:
      context: ./backend
      dockerfile: DockerFileBackendFRA
    container_name: backendFRA
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebFRA
  web:
    build:
      context: ./web
      dockerfile: DockerfileWebFRA
    container_name: webFRA
    ports:
      - "80:80" # si tienes problemas con el puerto 80 cambia el puerto externo aquí
    networks:
      - redwebFRA
networks:
  redwebFRA:
    driver: bridge
